"""
Public REST API for Kairos (flask-smorest).

Distinct from app/routes/ (session-cookie/Flask-Login, HTML/legacy JSON
responses): every blueprint registered here is authenticated by a
ServiceAccount bearer token (app/auth/service_account_auth.py), never a
cookie, and always returns JSON (see app/api/errors.py for why that
needs an explicit per-blueprint error handler). URL prefix is
/api/v1/*, deliberately distinct from the internal /api/* routes
(app/routes/shift_routes.py etc., cookie-based) to avoid any collision.

OPENAPI_SWAGGER_UI_PATH/OPENAPI_REDOC_PATH/OPENAPI_RAPIDOC_PATH are
deliberately left unset: flask-smorest's default UIs pull their JS/CSS
from CDNs that aren't in this app's CSP_POLICY (app/__init__.py). The
interactive documentation this app DOES serve (GET /api/v1/docs,
Scalar, see app/api/docs_view.py) instead loads its one JS bundle from
cdn.jsdelivr.net, an origin already CSP-whitelisted for FullCalendar -
no CSP change needed, so it was worth adding despite the constraint
that ruled out flask-smorest's own default UIs. The raw spec
(/api/v1/openapi.json) stays independently reachable either way,
usable in an external Swagger UI/Postman/Insomnia instance too.
"""

from flask import Flask
from flask_smorest import Api

api = Api()


def init_api(app: Flask) -> None:
    """Registers the already-configured resource blueprints (auth
    hook + JSON error handlers, see app/api/setup.py) on this specific
    app instance. Safe to call on every create_app() - unlike the
    per-blueprint setup calls, api.register_blueprint() (a thin wrapper
    around Flask's own app.register_blueprint()) is meant to run once
    per app instance, not once per process."""
    app.config.setdefault("API_TITLE", "Kairos Public API")
    app.config.setdefault("API_VERSION", "v1")
    app.config.setdefault("OPENAPI_VERSION", "3.0.3")
    app.config.setdefault("OPENAPI_URL_PREFIX", "/api/v1")
    app.config.setdefault("OPENAPI_JSON_PATH", "openapi.json")

    # Extra kwargs merged into apispec.APISpec by flask-smorest - built
    # fresh per create_app() call (not registered imperatively via
    # api.spec.components.security_scheme(), which would need its own
    # duplicate-registration guard across the many app instances this
    # process can build, e.g. one per test). PUBLIC_BASE_URL (existing
    # setting, see app/config/base.py) is reused as-is for the server
    # origin - falls back to a relative "/" (never request.host_url's
    # internal hostname) when unset, per the "safe relative behavior"
    # requirement for an unconfigured instance.
    app.config["API_SPEC_OPTIONS"] = {
        "info": {
            "description": (
                "Read-only REST API for third-party integrations with "
                "Kairos. Authentication is performed using ServiceAccount "
                "bearer tokens (see the ServiceAccountBearer security "
                "scheme below). Requests are rate-limited per "
                "ServiceAccount; limits are configured by the Kairos "
                "instance administrator (API_RATE_LIMIT) rather than "
                "fixed by the protocol - the default installation uses "
                "60 requests per minute and 1000 requests per day. A "
                "breached limit returns 429."
            ),
            "license": {"name": "CeCILL-2.1"},
            "contact": {"url": "https://github.com/FoxOps/kairos"},
        },
        "externalDocs": {
            "description": "Kairos project on GitHub",
            "url": "https://github.com/FoxOps/kairos",
        },
        "servers": [
            {
                "url": app.config.get("PUBLIC_BASE_URL") or "/",
                "description": "Kairos server",
            }
        ],
        "components": {
            "securitySchemes": {
                "ServiceAccountBearer": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "Kairos ServiceAccount token",
                    "description": (
                        "ServiceAccount token generated by a Kairos "
                        "administrator (/admin/service-accounts)."
                    ),
                }
            }
        },
        "security": [{"ServiceAccountBearer": []}],
    }

    api.init_app(app)

    from app.api.resources import all_blueprints

    for blp in all_blueprints:
        api.register_blueprint(blp)

    from app.api.docs_view import register_docs_views

    register_docs_views(app)
