apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kairos
  namespace: kairos
  labels:
    app: kairos
spec:
  minAvailable: 1
  # ou maxUnavailable: 1
  selector:
    matchLabels:
      app: kairos
