apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: leviia-schedule
  namespace: leviia-schedule
  labels:
    app: leviia-schedule
spec:
  minAvailable: 1
  # ou maxUnavailable: 1
  selector:
    matchLabels:
      app: leviia-schedule
