services:
  leviia-schedule:
    image: leviia-schedule:optimized
    container_name: leviia-schedule
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - data:/app/data
      - logs:/app/logs
    user: "1000:1000"
