version: '3.8'

services:
  web:
    environment:
      - FLASK_ENV=development
      - DEBUG_ERRORS=true
      - SQLALCHEMY_ECHO=true
      - SESSION_COOKIE_SECURE=false
      - RATE_LIMIT_ENABLED=false
    volumes:
      - ..:/app:ro
    ports:
      - "5678:5678"

networks:
  leviia-net:
    external: true
