"""baseline: initial schema

Revision ID: da2c4dfc1024
Revises:
Create Date: 2026-07-15 12:04:59.628753

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "da2c4dfc1024"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_config",
        sa.Column("config_key", sa.String(length=80), nullable=False),
        sa.Column("config_value", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("config_key"),
    )
    with op.batch_alter_table("automation_config", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_automation_config_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_automation_config_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "groups",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("is_part_of_schedule", sa.Boolean(), nullable=True),
        sa.Column("is_part_of_oncall", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_groups_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_groups_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "shift_types",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.Column("start_hour", sa.Integer(), nullable=False),
        sa.Column("end_hour", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("shift_types", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shift_types_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_shift_types_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "user",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("ics_token", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("ics_token"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_group_id"), ["group_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "app_notification",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notification_type", sa.String(length=30), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("app_notification", schema=None) as batch_op:
        batch_op.create_index(
            "idx_app_notification_user_read", ["user_id", "read_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_app_notification_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_app_notification_updated_at"), ["updated_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_app_notification_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "leave",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("leave", schema=None) as batch_op:
        batch_op.create_index(
            "idx_leave_user_date_range",
            ["user_id", "start_date", "end_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_leave_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_leave_end_date"), ["end_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_leave_start_date"), ["start_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_leave_updated_at"), ["updated_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_leave_user_id"), ["user_id"], unique=False)

    op.create_table(
        "notification_log",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notification_type", sa.String(length=20), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "notification_type",
            "period_start",
            name="uq_notification_log_user_type_period",
        ),
    )
    with op.batch_alter_table("notification_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_log_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_log_updated_at"), ["updated_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_log_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "on_call",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("on_call", schema=None) as batch_op:
        batch_op.create_index(
            "idx_oncall_user_start_end",
            ["user_id", "start_time", "end_time"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_on_call_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_on_call_end_time"), ["end_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_on_call_start_time"), ["start_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_on_call_updated_at"), ["updated_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_on_call_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "shift",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("shift_type_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shift_type_id"],
            ["shift_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shift", schema=None) as batch_op:
        batch_op.create_index(
            "idx_shift_date_start", ["date", "start_time"], unique=False
        )
        batch_op.create_index("idx_shift_user_date", ["user_id", "date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_shift_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_shift_date"), ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_shift_end_time"), ["end_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_shift_shift_type_id"), ["shift_type_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_shift_start_time"), ["start_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_shift_updated_at"), ["updated_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_shift_user_id"), ["user_id"], unique=False)

    op.create_table(
        "swap_request",
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.Column("shift_id", sa.Integer(), nullable=False),
        sa.Column("target_user_id", sa.Integer(), nullable=False),
        sa.Column("target_shift_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("admin_comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shift.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_shift_id"],
            ["shift.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("swap_request", schema=None) as batch_op:
        batch_op.create_index(
            "idx_swap_requester_status", ["requester_id", "status"], unique=False
        )
        batch_op.create_index(
            "idx_swap_target_status", ["target_user_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_swap_request_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_swap_request_requester_id"), ["requester_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_swap_request_reviewed_by_id"),
            ["reviewed_by_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_swap_request_shift_id"), ["shift_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_swap_request_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_swap_request_target_shift_id"),
            ["target_shift_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_swap_request_target_user_id"),
            ["target_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_swap_request_updated_at"), ["updated_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("swap_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_swap_request_updated_at"))
        batch_op.drop_index(batch_op.f("ix_swap_request_target_user_id"))
        batch_op.drop_index(batch_op.f("ix_swap_request_target_shift_id"))
        batch_op.drop_index(batch_op.f("ix_swap_request_status"))
        batch_op.drop_index(batch_op.f("ix_swap_request_shift_id"))
        batch_op.drop_index(batch_op.f("ix_swap_request_reviewed_by_id"))
        batch_op.drop_index(batch_op.f("ix_swap_request_requester_id"))
        batch_op.drop_index(batch_op.f("ix_swap_request_created_at"))
        batch_op.drop_index("idx_swap_target_status")
        batch_op.drop_index("idx_swap_requester_status")

    op.drop_table("swap_request")
    with op.batch_alter_table("shift", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shift_user_id"))
        batch_op.drop_index(batch_op.f("ix_shift_updated_at"))
        batch_op.drop_index(batch_op.f("ix_shift_start_time"))
        batch_op.drop_index(batch_op.f("ix_shift_shift_type_id"))
        batch_op.drop_index(batch_op.f("ix_shift_end_time"))
        batch_op.drop_index(batch_op.f("ix_shift_date"))
        batch_op.drop_index(batch_op.f("ix_shift_created_at"))
        batch_op.drop_index("idx_shift_user_date")
        batch_op.drop_index("idx_shift_date_start")

    op.drop_table("shift")
    with op.batch_alter_table("on_call", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_on_call_user_id"))
        batch_op.drop_index(batch_op.f("ix_on_call_updated_at"))
        batch_op.drop_index(batch_op.f("ix_on_call_start_time"))
        batch_op.drop_index(batch_op.f("ix_on_call_end_time"))
        batch_op.drop_index(batch_op.f("ix_on_call_created_at"))
        batch_op.drop_index("idx_oncall_user_start_end")

    op.drop_table("on_call")
    with op.batch_alter_table("notification_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_log_user_id"))
        batch_op.drop_index(batch_op.f("ix_notification_log_updated_at"))
        batch_op.drop_index(batch_op.f("ix_notification_log_created_at"))

    op.drop_table("notification_log")
    with op.batch_alter_table("leave", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leave_user_id"))
        batch_op.drop_index(batch_op.f("ix_leave_updated_at"))
        batch_op.drop_index(batch_op.f("ix_leave_start_date"))
        batch_op.drop_index(batch_op.f("ix_leave_end_date"))
        batch_op.drop_index(batch_op.f("ix_leave_created_at"))
        batch_op.drop_index("idx_leave_user_date_range")

    op.drop_table("leave")
    with op.batch_alter_table("app_notification", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_app_notification_user_id"))
        batch_op.drop_index(batch_op.f("ix_app_notification_updated_at"))
        batch_op.drop_index(batch_op.f("ix_app_notification_created_at"))
        batch_op.drop_index("idx_app_notification_user_read")

    op.drop_table("app_notification")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_updated_at"))
        batch_op.drop_index(batch_op.f("ix_user_group_id"))
        batch_op.drop_index(batch_op.f("ix_user_created_at"))

    op.drop_table("user")
    with op.batch_alter_table("shift_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shift_types_updated_at"))
        batch_op.drop_index(batch_op.f("ix_shift_types_created_at"))

    op.drop_table("shift_types")
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_groups_updated_at"))
        batch_op.drop_index(batch_op.f("ix_groups_created_at"))

    op.drop_table("groups")
    with op.batch_alter_table("automation_config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_config_updated_at"))
        batch_op.drop_index(batch_op.f("ix_automation_config_created_at"))

    op.drop_table("automation_config")
    # ### end Alembic commands ###
