"""Phase 3 scenario test: fresh 6-month generation vs. six successive
monthly generations must assign the identical user to every shared
Friday - the direct regression test for audit defect #4 (on-call
rotation resetting every generation call because week_index was an
enumerate() position local to that call's own week list). No DB/app
context needed - plan_oncalls_for_scope() is pure."""

from datetime import date, timedelta

from app.utils.automation.planner.oncall_planner import plan_oncalls_for_scope
from app.utils.automation.planner.rotation import absolute_week_index
from app.utils.automation.planner.types import OnCallSnapshot, ResolvedRules, UserRef

RULES = ResolvedRules(
    oncall_anchor_weekday=4,
    oncall_anchor_start_hour=21,
    oncall_anchor_end_hour=7,
    oncall_spacing_weeks=2,
    weekend_days=frozenset({5, 6}),
    staffing_limits={},
    rest_after_oncall_hours=0,
    oncall_shift_overlap_block=False,
    oncall_shift_type_id=100,
    oncall_slot_hours=(13, 21),
    rotation_shift_type_id=200,
    rotation_slot_hours=(7, 15),
    default_shift_type_id=300,
    default_slot_hours=(9, 17),
)
EPOCH = date(2000, 1, 3)
USERS = tuple(UserRef(id=i, name=f"U{i}", group_id=None) for i in (1, 2, 3, 4))


def _plan(start, end, existing_oncalls=()):
    return plan_oncalls_for_scope(
        start_date=start,
        end_date=end,
        group_id=None,
        rotation_order=USERS,
        rotation_anchor_epoch=EPOCH,
        existing_oncalls=existing_oncalls,
        existing_leaves=(),
        locked=frozenset(),
        published={},
        rules=RULES,
    )


def _next_month_start(d: date) -> date:
    return date(d.year + 1, 1, 1) if d.month == 12 else date(d.year, d.month + 1, 1)


def test_absolute_week_index_advances_by_one_per_week():
    fridays = [date(2026, 1, 2), date(2026, 1, 9), date(2026, 1, 16)]
    indices = [absolute_week_index(f, EPOCH) for f in fridays]
    assert indices[1] == indices[0] + 1
    assert indices[2] == indices[0] + 2


def test_six_month_generation_matches_six_monthly_generations():
    full = _plan(date(2026, 1, 1), date(2026, 6, 30))
    full_by_friday = {p.friday: p.user_id for p in full.proposed}

    # Six independent monthly calls, each only knowing about on-calls
    # already generated by the prior calls - exactly how an admin
    # clicking "Generate" once per month, one month at a time, would
    # behave. Existing on-calls must be threaded forward for a fair
    # comparison: the spacing constraint is legitimately aware of
    # cross-month history in both the single 6-month call and this
    # accumulating sequence of monthly ones.
    accumulated: list[OnCallSnapshot] = []
    month_start = date(2026, 1, 1)
    while month_start <= date(2026, 6, 30):
        month_end = _next_month_start(month_start) - timedelta(days=1)
        fragment = _plan(month_start, month_end, existing_oncalls=tuple(accumulated))
        for proposed in fragment.proposed:
            assert full_by_friday[proposed.friday] == proposed.user_id, (
                f"Friday {proposed.friday}: monthly call assigned "
                f"{proposed.user_id}, full 6-month call assigned "
                f"{full_by_friday[proposed.friday]}"
            )
            accumulated.append(
                OnCallSnapshot(
                    user_id=proposed.user_id,
                    group_id=None,
                    start_time=proposed.start_time,
                    end_time=proposed.end_time,
                )
            )
        month_start = _next_month_start(month_start)


def test_two_adjacent_refresh_calls_do_not_reset_rotation():
    """Two consecutive 'Rafraichir' calls on adjacent date ranges,
    each aware of the other's prior assignments (as a real refresh
    would be, via the DB), must not restart the rotation offset - each
    call's own local week_index must never affect the result."""
    whole_range = _plan(date(2026, 1, 1), date(2026, 2, 28))
    whole_by_friday = {p.friday: p.user_id for p in whole_range.proposed}

    first = _plan(date(2026, 1, 1), date(2026, 1, 31))
    first_snapshots = tuple(
        OnCallSnapshot(
            user_id=p.user_id,
            group_id=None,
            start_time=p.start_time,
            end_time=p.end_time,
        )
        for p in first.proposed
    )
    second = _plan(
        date(2026, 2, 1), date(2026, 2, 28), existing_oncalls=first_snapshots
    )

    for proposed in first.proposed:
        assert whole_by_friday[proposed.friday] == proposed.user_id
    for proposed in second.proposed:
        assert whole_by_friday[proposed.friday] == proposed.user_id
